#!/bin/bash

SUBNET=$(echo $IP | cut -d . -f 1-3)
sed -i "s#GW#$GW#" /etc/dhcp/dhcpd.conf
sed -i "s#SUBNET#$SUBNET#" /etc/dhcp/dhcpd.conf
sed -i "s#DHCP_SERVER#$IP#" /etc/dhcp/dhcpd.conf
sed -i "s#DHCP_RANGE#$DHCP_RANGE#" /etc/dhcp/dhcpd.conf
[ ! -f '/var/lib/tftpboot/num' ] && echo 1 > /var/lib/tftpboot/num

if [ ! -d '/var/lib/tftpboot/pxelinux.cfg' ];then
    mkdir /var/lib/tftpboot/pxelinux.cfg
    echo '# create new' >> /var/lib/tftpboot/pxelinux.cfg/default
    echo 'timeout 100' >> /var/lib/tftpboot/pxelinux.cfg/default
    echo 'default menu.c32' >> /var/lib/tftpboot/pxelinux.cfg/default
    echo -e '\nmenu title ############# PXE Boot Menu #############' >> /var/lib/tftpboot/pxelinux.cfg/default
    echo 'label 0' >> /var/lib/tftpboot/pxelinux.cfg/default
    echo '    menu label ^0) Boot from local drive' >> /var/lib/tftpboot/pxelinux.cfg/default
    echo -e '    localboot' >> /var/lib/tftpboot/pxelinux.cfg/default
    cp /opt/{menu.c32,pxelinux.0} /var/lib/tftpboot
fi
